language: ruby
rvm:
  - 2.2.5
  - 2.3.1
branches:
  only:
    - master
    - develop
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
